addons:
  sonarqube: true
env:
  global:
    secure: "taWXSD6auhW09r7pslvGcbtvLYzh13CGm9eF1JPGyDqZkLBFc2ARwoYGCkzfj8TrlgieHk5r18SNExbYARdM95NGIaPffo+jgEJAPye9T65OBbU4zY32BuM8oYiveFgZCBbeVaaSYzRvh/Dk5npoXAwJEuQ+TIgeDBDg4vBqpDJJpPaczqfL08v/s+zaKeA6S5y9NChnJWsa3rgWkxu/nYNqKVC2i62M25uAZKVdadvB8BjHmxNuF12G5XrFjClxuENo5GxHgYeAy6fnPGMV9NsbH0dUq9NloGfyfxe0iXNV7QIY0ctfsKrsS7ZEmaHjzuelB9E/1ke0FtPDmaQ8QGH+EE1hlj2wuTbGJc3ND4DuEfLBlFLG57cRkbXyyhO9xtrwYUhujWYIMwCoXZpPhzrOUi7WLbnJSraai6gkoxMaM4xz+I0qc5b/UJWprkpth7SzEXDO75lEe5KxWEMjoFQl5N5KiSclRFHXO1nD1SVVGRZEOCQwlxaGBZeDqQzIqhhycYJPzEXbFfzrDjULNoxs15PbM623qP2wul7WR+ksRYCJ949oWjW4cWgiLxsuCfPtTCXu665N3KH4BePyDBtORzN5inYZcHp5UdnX1aZvqZtdLMqgjxwrg8jmwj00ZXGkf6TYgXq/pUoUjBqcFJhA2AY/WkdOl/7ALTM0afY="

language: java
install: /bin/true
before_install:
 - chmod +x gradlew
script:
 - ./gradlew check
 - ./gradlew sonarqube -DSONARQUBE_TOKEN=$SONAR_TOKEN
